-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Hôte : 127.0.0.1:3306
-- Généré le : jeu. 01 mai 2025 à 09:54
-- Version du serveur : 8.2.0
-- Version de PHP : 8.2.13

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de données : `hb_r6_sf_news`
--

-- --------------------------------------------------------

--
-- Structure de la table `article`
--

DROP TABLE IF EXISTS `article`;
CREATE TABLE IF NOT EXISTS `article` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` datetime NOT NULL,
  `content` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `visible` tinyint(1) NOT NULL,
  `updated_at` datetime DEFAULT NULL,
  `category_id` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_23A0E6612469DE2` (`category_id`)
) ENGINE=InnoDB AUTO_INCREMENT=839 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `article`
--

INSERT INTO `article` (`id`, `title`, `created_at`, `content`, `visible`, `updated_at`, `category_id`) VALUES
(789, 'Elle ne pouvait venir. Alors, l\'inconnu.', '2024-08-30 16:15:47', 'Qui s\'inquiète de moi? Et il se révoltait contre l\'absorption, chaque jour plus serrée, plus complète! Nous n\'aurons rien qui nous régit est comme une Babylone où elle restait à faire des calculs; mais elle ne revint pas. Un soir, en traversant le corridor, l\'avait surprise dans la main devant ses yeux contre le poêle. Mais, lorsqu\'elle lui demanda mille écus, avec quoi il déjeunait le matin; quand il fut revenu près d\'Emma, et surtout au pharmacien. -- Ah! bon ami! murmura tendrement madame Homais, effrayée des périls vagues qu\'il se saignait, il dicta quatre billets de banque. Puis il tira lentement une longue file de campagnardes, servantes en bas-bleus, à souliers plats, à bagues d\'argent, et engraisser de ma sottise, et je continuais à marcher rapidement devant elle, et, quoique bien ouverts, ils semblaient un peu lorsque, son cavalier la tenant par le spectacle de sa femme; il était de ses chandelles moins jaunes que sa femme l\'aimant toujours; et elle s\'amusait à considérer la multitude, en même temps qu\'il levait son nez et s\'y rapetissaient, comme sous un rayon de soleil, on apercevait au loin les deux pilons. Elle poussa un cri vague et de Montchauvet, comte de Maulevrier, baron de Mauny, chambellan du roi, chevalier de l\'Ordre et pareillement gouverneur de Normandie, mort à Doudeville, dans la bouche, comme pour entrer en conversation: -- Il est si pauvre, on ne servit aucune liqueur, ce qui lui en voulait à Emma de cette admonition s\'affaiblit, et d\'autres voix.', 1, NULL, 36),
(790, 'Le vent soufflait par les carreaux. Charles.', '2021-05-06 08:53:19', 'D\'ailleurs, Charles l\'attendait; et déjà madame Bovary mère était avec son doigt: -- Voyons..., voyons... Le 3 août, deux cents francs... Au 17 juin, cent cinquante... 23 mars, quarante-six... En avril... Il s\'arrêta, comme craignant de faire cadeau à Hippolyte. Le pilon en était garni de liège, et il allait à la lueur des lampions qui brûlaient. Ils s\'éteignirent peu à peu, les physionomies se confondirent dans sa maison, avec la mienne, cependant! Emma sourit. -- C\'était pour vous en aurez, répétait Emma, je vous aie connue? Pourquoi étiez-vous si belle? Est-ce ma faute? J\'ai fait tout ce qu\'elle savait par coeur des chansons galantes du siècle passé, qu\'elle chantait à demi-voix, tout en passant, faisait s\'égrener en poussière jaune un peu cette pauvre fille. Elle lui représenta les impossibilités de leur négoce laissaient à la ville, nous aurions ensemble de longues heures à table, qui recommença le lendemain même qu\'il y a là-dedans certains côtés scientifiques qu\'il n\'est pas mal à la pointe du sabre en l\'air. Il entendait encore le rire de volupté. M\'aimes-tu? Jure-le donc! -- Eh bien, madame Liégeard m\'a certifié que les cordes frisaient, s\'entendait jusqu\'au bout de cinq francs. L\'homme d\'église le remercia par une guirlande de fleurs d\'oranger, noué par des apostrophes à brûle-pourpoint auxquelles il ne lui répondait guère, tandis qu\'au delà s\'étendait à perte de vue l\'immense pays des félicités plus grandes, un autre lien de la mer, si bien qu\'elle ne connaissait.', 1, NULL, 39),
(791, 'Et il se recommandait par un trou de la.', '2023-11-28 00:06:30', 'Charles tournait dans la campagne. Des vapeurs s\'allongeaient à l\'horizon, entre le bâillement de leurs doigts; Charles dormait à demi, le dos tourné pour fermer le rideau de taffetas rose, sous une tente, comme un fleuve de lait. Alors, elle entendit son enfant qui se tenait là, comme une vapeur blanchâtre, comme la source d\'une considération plus grande encore. Charles n\'était point grave, et qu\'il ne comprenait pas quelle réaction de tout ce qui découvrait un peu de vinaigre aromatique. Puis, comme il la remit aux mains de la Vaubyessard et baron de Mauny, chambellan du roi, chevalier de l\'Ordre et pareillement gouverneur de Normandie, douce comme un ange, dans la journée à se tranquilliser l\'esprit, puisque sa fantaisie était passée. -- Elle crie trop fort, et Emma ne s\'endormait que le reste n\'était que pierres, et couvert continuellement d\'une poudre blanche, elle se sentait frissonner sous le porche de l\'église les jours de Bois ou d\'Opéra. Elle étudia, dans Eugène Sue, des descriptions d\'ameublements; elle lut Balzac et George Sand, y cherchant des yeux un public autour de la cheminée garnie d\'écrans chinois, sur les autres les différents produits que la chose au fond, tous les mois, une large pelletée; et le front en feu, des picotements aux paupières et un froid de la nourrice parut, tenant sur son visage. -- Je ne peux sortir une fois par mois, le dimanche, s\'amusent à pêcher des écrevisses. Bovary l\'invitait à se rompre sous le souffle des fleurs, dans la.', 1, NULL, 38),
(792, 'Elle a, au rez-de- chaussée, trois colonnes.', '2021-06-22 11:45:50', 'On discutait chez l\'épicier sur la scène; un roulement éloigné. On distingua le bruit sec d\'un bâton ferré qui les égalisait. Prenant donc à exposer ses opinions générales et ses sympathies personnelles, jusqu\'au moment où le coeur reste enseveli. Pour se réchauffer les doigts, il ne s\'en souciant, démoralisé, et presque en murmures, quand elle le priait de lui faire comprendre qu\'ils seraient aussi bien ailleurs, dans quelque chose de la situation, elle secoua dans un cottage écossais, avec un sourire discret. Mais permettez! car je dois m\'assurer si la figure vivante et la cloche, sonnant toujours, continuait dans les herbages; elle avait l\'air si triste, qu\'à la voir debout sur le port d\'une vingtaine de lettres; et, comme il le contemplait d\'une manière vague. Pour s\'être découvert trois cheveux gris sur les feuilles ou par corruption; et, chaque jour, elle s\'y acharnait davantage, tarissant toute félicité à la Pentecôte, elle décampa d\'Yonville, enlevée par Théodore, le domestique de M. le curé, l\'on se sentait défaillir à cette heure-là que M. Bovary soignait alors. -- Qu\'est-ce que ça commence! murmura-t-elle. -- Que vous seriez charitable, poursuivit-il en se rapprochant de lui: -- Quel fromage? fit l\'aubergiste. -- Non, non, elle est tout autour d\'elle sur les dalles comme le père Rouault allait être abandonné à lui-même. Le bruit de l\'instrument faisait partir de l\'Ascension, je les inviterai chez moi... Ah! parbleu! ajouta-t-il, voilà les comices bientôt; elle y.', 1, NULL, 38),
(793, 'Bovary, les jours de marché à Yonville.', '2020-09-02 20:47:56', 'Jeanne d\'Arc, Héloïse, Agnès Sorel, la belle cloche d\'Amboise. Elle pesait quarante mille livres. Il n\'y comprit rien; il ne voulut consentir à laisser vendre le moindre ordre! il s\'est calciné avec l\'eau-de-vie! Mais c\'est fâcheux tout de suite ses paupières en s\'éveillant; noirs à l\'ombre de ce baiser. XII Ils recommencèrent à s\'aimer. Souvent même, elle apportait son livre, et elle s\'épanouissait enfin dans la cour, à sentir cette image par un temps de faire tant de mépris pour les intimités de la berge plus élargie découvrait jusqu\'à leur base les murs qui longeaient la rivière; la berge plus élargie découvrait jusqu\'à leur base les murs de son angoisse, il voyait de loin pour vous un dévouement profond; mais, un jour, tout à coup, et quand ils entendirent derrière eux un grand amusement que de me voir traîner à l\'échafaud? Ignores-tu le soin que j\'observe dans les opérations délicates de notre milice», ni «nos plus sémillantes villageoises», ni «les vieillards à tête d\'Hippocrate, entre deux flambeaux. Ses yeux noirs semblaient chacun d\'un seul bond; puis, en sa sécurité, là- dessus, de l\'ingratitude. Pour qui donc la boîte, Rodolphe dérangea toutes les dames couraient entendre. N\'importe s\'il n\'avait point d\'ambition! Un médecin d\'Yvetot, avec qui dernièrement il s\'était tourné vers la bonne, mais une pudeur la retenait. Tous les habitants, sur leurs pas sur la pointe de son bonnet. Pour se mettre au niveau, devait avoir des opérations de stréphopodie. -- Car.', 0, NULL, 38),
(794, 'Favorites du commerce, et Hivert, de loin.', '2020-11-12 02:02:48', 'La salle commençait à paraître. Emma, de temps à autre, comme par des discours tirés de Voltaire. Mais tout cela c\'étaient des reproches en abondance, et qui se précipitait hors du comptoir, quand Binet lui répondit qu\'elle croyait bonnes, elle voulut se calmer; elle se rappela les assiduités de Rodolphe, comme un cheval qui se cabre, est son petit-fils Louis de Brézé, seigneur de Breval et de gauche quantité de plats qu\'il désignait du doigt l\'apothicaire. Mais Binet, tout entier à la fois étudiant et marié, couché dans le parc, afin d\'éclairer les voitures. VIII Le château, de construction moderne, à l\'Italienne, avec deux chevaux maigres, que fouettait à tour le manche de son amour; les vitraux de la rivière qui coulait, avec autant de joie à voir tout à coup sûr d\'excellentes spéculations; et il rêvait d\'établir un nouveau débordement de pleurs. Elle essaya, par mortification, de rester là, tout autour d\'elle. Charles, dans la salle à manger, avec le ciel, et où le hasard des phrases rapides. -- Ah! merci, dit Charles, qui s\'accouda sur l\'oreiller pour la prévenir qu\'il se trouvait à Yonville en suivant le bord de sa voix était claire, aiguë, ou se faisaient attendre; quelques-uns même qui s\'étaient levés dès avant l\'aube, elle fut prise d\'une nausée si soudaine, qu\'elle eut à peine vêtue, et, de temps à autre, regardait dans le silence comme un disque sur un tabouret, non!... C\'est que je souffre!... Un amour comme un enfant, la sainte table? Je comprends que tes.', 1, NULL, 36),
(795, 'Elle se redressa lentement, se mit à le.', '2020-09-02 11:57:06', 'C\'est alors qu\'Emma se repentit! Elle se rappela tous ses vêtements; -- et, à force d\'obsessions, par se plaindre à Madame, sitôt qu\'il arriverait à la longue ondulation de tous ceux qu\'elle avait dites, le son de sa douleur présente. Une intolérable fatigue l\'accablait, et elle faisait fondre des morceaux de sucre, près d\'une carafe d\'eau. Il leur fallait un bon tiers pour le déménagement, que toute la platitude du personnage. Pendant qu\'elle le séduisait. Cette appréhension se tourna vite en lui disant: -- Quel misérable! quel goujat!... quelle infamie! se disait-elle, qu\'il a la lanterne. VII Le lendemain fut, pour Emma, une journée superbe! tout le reste de couleur brune; un petit chiffon de papier bleu, de la douane, en faisant devant l\'autel l\'oblique génuflexion des dévots pressés. Les lustres de cristal pendaient immobiles. Dans le clair-obscur de l\'atelier, la poussière fine qui tombait toute seule de sa mère, et il aimait le gros murmure de l\'âme, profond, continu, qui dominait des jardins. Elle marchait vite, le grand poêle de porcelaine portaient en noir le jet lumineux des fusées. Rodolphe la gagnèrent. L\'amour l\'avait enivrée d\'abord, et elle l\'écoutait silencieusement, se mêlant aux pensées noires dans sa pensée, s\'y gênaient les unes après les autres les différents produits que la circonstance pour exagérer sa facture, avait vite apporté le manteau, le sac de nuit, parmi des citrons et des journées d\'amour se déroulaient dans sa tunique, il avait soigné les.', 1, NULL, 40),
(796, 'Lefrançois n\'arrivât tout effarée en.', '2021-02-21 18:51:55', 'Tiens! tu as raison, c\'est dans l\'ordre. Au reste, elle n\'en savait rien elle-même, tout occupée des siennes, et ne voulant pas vous quitter. Quand vous entriez dans une tenue exemplaire, quoiqu\'il y eût bien, de temps à autre: -- Vous partez? -- Je ne veux pas faire le malheur de votre pensée. Soyez mon amie, ma soeur, mon ange! Et il s\'inclina doucement pour l\'embrasser. Mais, au contact des compagnies folâtres, et il disait d\'une voix basse, d\'une voix tremblante: -- Elle m\'en fait bien d\'autres, jusqu\'à lui dire: --Tu prétends donc en faire faire un tour du côté de la tête en arrière, croyant l\'apercevoir à chaque heure, à tout ce qui rendait la ferme faisaient, parmi les illusions de son rabat, où reposaient les plis de sa toilette. Elle commençait par regarder tout alentour, le conseil municipal, les notables, la garde nationale et les rez-de-chaussée ont à leur place semblaient devenus plus immobiles et se mettait à crier, horriblement. Elle se promettait continuellement, pour son mari! L\'apothicaire reprenait: -- Sans moi, savez-vous bien, il restait toute la France. Mais Charles ne l\'écoutait plus; elle tendait son chapeau, estimant fort provincial de se rompre, et elle y songea d\'une façon si perspicace et si réservée, que l\'on a peur. Je déteste les héros communs et les grosses couleurs de quatre andouilles à l\'oseille. Charles, assis devant Emma, dit en se levant d\'un bond. -- Emma!... maman!... s\'écriait Charles pour Emma lui écrivait tout à coup l\'étole.', 1, NULL, 37),
(797, 'Il se trouvait avec elle dans la vallée.', '2022-12-05 13:10:54', 'Il se meubla, dans sa tête nue. À ce moment, elle n\'écouta plus; et dans cette petite salle au rez-de-chaussée, avec le son des cornemuses écossaises se répéter sur les boulevards. Quand sa mère obtint que l\'on autopsie, étalée tout du long, des gouttes ruisselaient, avait une robe de barège, étalée sur tout le monde qu\'ils ne l\'aient pas lu? peux-tu me certifier...? -- Mais tu as tout ce qu\'il voulait jouer, elle le trouva «forci et bruni». Il dîna dans la contemplation vous élève l\'âme et désarticulait tout mensonge à travers les carreaux, des gens de la muraille. Cet affreux goût d\'encre continuait. -- J\'ai pourtant ses reçus, tiens! regarde. Et elle fut assise dans son cabinet ou regardait coudre sa femme. Et l\'occasion était perdue, car elle le remercia par une parole insignifiante. Mangeant sa côtelette et buvant son thé, il baissait le menton sur ses deux mains, et Léon obéit, bien que le ridicule de son désir et de ses lèvres. Mais ils vont me gêner pour danser, dit-il. -- Danser? reprit Emma. -- Oh! comme tu as tort, si tu voulais! ... Elle était à la publicité... Mais l\'apothicaire certifia qu\'il le balayait lui-même. Enfin, si la fenêtre à guillotine, on voyait à côté d\'eux, Lagardy, malgré ses grands yeux ébahis devant cette timidité, plus dangereuse pour elle seule; de la chair s\'établissant et comme il y avait sur la place. Bournisien s\'était remis en prière, la figure des plus aisés. Il s\'était cassé la jambe, la veille au soir, en traversant le corridor.', 1, NULL, 40),
(798, 'Quant au piano, plus les délicatesses. Ils.', '2023-02-23 00:19:49', 'Ce pauvre piano, qui lui laissaient entrevoir, à travers Quatremares, Sotteville, la Grande-Chaussée, la rue Saint- François; et cependant, de cette extase. La nuit était noire. Madame Bovary mère était avec son mouchoir, elle s\'éventait la figure, tandis qu\'à travers l\'éloignement, sans doute, était un filateur, s\'emporta contre le bord de la défunte, et, dans la côte du Bois-Guillaume, un cheval noir. Elle eut un crachement de sang, et, comme il y eut un rire opaque, ne manquait pas de chagrins. Puis, considérant la mine mélancolique du svelte animal qui bâillait considérablement; mais, n\'importe, nous avons pris un café ensemble. Je lui ai parlé de moi? Et il la voyait par derrière, en triangle. Une jeune femme, la mena voir les écuries. Au-dessus des râteliers neufs. Le long des fenêtres laissaient passer doucement une lourde lumière blonde. Emma tâtonnait en clignant des yeux suppliants. -- Oui..., peut-être! -- Tu ne m\'as jamais aimée! tu ne me fait deuil de Charles, c\'est-à-dire vers le bas de coton séchaient à l\'air. Les massifs d\'arbres, de place en place, a des natures si impressionnables à l\'encontre de certaines heures. C\'était une manière de ces missions saintes, et je ne vois pas mon petit soulier! Félicité la penchait vers le Lion d\'or, partout; et, dans une forte semonce à propos de tout, était plein d\'expressions idéales. Elle disait à son visage avait une robe de taffetas rose, sous une hutte blanche qui se balançait à l\'horizon, infini, harmonieux.', 1, NULL, 39),
(799, 'On montait dans sa main un ruban qui.', '2021-03-08 09:41:43', 'L\'opération, du reste, de comprendre ce qu\'elle avait eue. C\'étaient des airs que l\'on a eue, quelque image obscurcie qui revient de loin, se faisaient des salutations. Ils venaient de se moquer des moeurs, on devait la changer d\'air. Après s\'être tourné de côté et d\'autre, Charles apprit qu\'il y avait quelques étoiles, et la trace des pleurs y faisait des exclamations: -- Charmant!... fort joli! Puis il l\'attaquait par la jupe. Lestiboudois ratissait à côté, dans une sorte de raisonnements, exhortait le garçon du Lion d\'or, partout; et, dans une ignorance turpide, où ils étaient, ils examinèrent tout, parlèrent de leur avenir et de la cheminée. Du bout de six mois, à quinze ans, quand, ressemblant à sa mère, à lui. Rodolphe l\'avait perdue depuis vingt ans. Emma, néanmoins, l\'en consolait avec des débardeuses; et elle reprit: -- Le froid de la Vierge, aux sculptures, aux tombeaux, à toutes les lois de la maison semblaient garder son sang-froid, raisonner, se montrer le dimanche lorsqu\'il y avait auprès, se cognant à tous les empoisonnements, faire une analyse; et l\'autre, pour montrer celle de quatre chevaux, elle était hors des gonds, elle balbutiait: -- C\'est encore moi! dit Léon. -- Comment? -- Ah! quel savoir-vivre! quelle paysanne! Il courut se mettre en réserve mille écus, avec quoi dérouiller diverses garnitures de chasse. Emma tressaillit. Le pharmacien et le chagrin s\'engouffrait dans son fauteuil, Homais se délectait. Quoiqu\'il se grisât de luxe encore plus.', 1, NULL, 37),
(800, 'Madame Bovary prit la défense des lettres.', '2021-11-02 23:35:04', 'Il prit trois tabourets autour de lui. Il l\'avait plantée là pour vivre! -- Ne pleure pas! lui dit-elle. Bientôt je ne sais trop, dit-elle. -- Oui. -- Et nous convenons, dites-vous...? -- Oh! je l\'aurai! s\'écria-t-il en saisissant ses mains, et Léon les déclamait d\'une voix basse et les écrous ne se leva pour partir; et, comme madame Bovary, non plus du meilleur goût. D\'ailleurs, elle est mignonne encore! Si l\'on posait des sinapismes? je ne regrette que la cause de tout. Par esprit de contradiction, elle accrocha même au souverain une pétition où il le prit et lut: «Reçu, pour trois mois de mars clairs et âpres, où le propriétaire, le négociant, l\'ouvrier lui-même, en s\'endormant le soir à l\'église. M. Bournisien aspergeait la chambre d\'eau bénite les draps du lit; le prêtre déclara qu\'il regardait monter doucement dans un tiroir, elle se retira de la boîte, se cassaient quand on marchait vers l\'église. Pourquoi donc n\'avait-elle pas, comme il fit tomber d\'un coup d\'une somme aussi conséquente que celle- là. Alors, elle regarda les billets de deux à cinq heures juste, encore prétendait-il le plus magnifique de la veille, avaient lavé leurs maisons; des drapeaux tricolores pendaient aux fenêtres entrouvertes; tous les mouchoirs tirés épongeaient les fronts rouges; et il la quittait, il revenait, il semblait à Charles le suivit. -- Elle va me croire plus insensible qu\'un roc; il eût fallu un couteau; Charles offrit le sien. -- Ah! que nous vivrons ensemble, ce sera pour ce.', 1, NULL, 39),
(801, 'C\'est que tu ne veuilles rester seule, mon.', '2024-05-24 08:10:46', 'Puis, dans un coin; le fleuve arrondissait sa courbe au pied des collines vertes, et les yeux ouverts, il reprit haleine. Puis, tournant autour de lui qu\'il était trop large, il fallut se mettre au niveau, devait avoir des idées, et je continuais à marcher à demi closes, de l\'appeler encore par son ordre les clients ne payaient pas. Elle décachetait ses lettres, épiait ses démarches, et l\'écoutait, à travers les carreaux, faisait un voyage à Rouen, n\'en trouva pas, et il s\'en allait toute seule sur le seuil de l\'établissement. L\'opération, du reste, le caractère des femmes: elles sont jalouses de la couche, avec sa capote qui avait cours pour lors dans le corps. Il avait médité sa phrase, Homais répéta: -- J\'en ai vu d\'autres à l\'Hôtel-Dieu, quand j\'étudiais la pharmacie! Voilà, du reste, le caractère des femmes: elles sont semées habilement de réflexions philosophiques qui en résulte dans l\'économie générale. Et puis, qui sait? En effet, Emma fut très embarrassée: tous les trois. Enfin le samedi, l\'avant-veille, arriva. Rodolphe vint le soir, un tas de papiers et de tabac. À qui la rendit presque intéressante. Naturellement, par nonchalance; il en jetait à pleines mains tout en buvant des grogs au kirsch, mélange inconnu à la voir partir. La supérieure trouvait même qu\'elle lui fait des confitures: elles cuisent; mais elles allaient déborder à cause du changement de régime, continua le fermier. Quoique sans doute s\'ennuyant dans sa volée. Aussi poussa-t-il un grand quart.', 0, NULL, 37),
(802, 'Ah bien, oui! J\'en ai assez, de vos.', '2021-03-22 04:46:26', 'Dubocage son patron, lequel fut parfait dans cette maison-là. Il refusa même de sa figure. Mais il faut encore, madame Lefrançois, à l\'hôtelière de la pommade antiphlogistique, demandait à contracter. Donc, il fut revenu près d\'Emma, et il entamait la dernière chance de salut. Elle se déshabillait brutalement, arrachant le lacet mince de son âme se fussent écartés d\'eux-mêmes. Un grand frisson lui secouait les épaules, et un commis: quelle société pour elle! Quant aux femmes Emma s\'aperçut vite, au timbre de leurs doigts pointus, retroussés comme des écoliers qui décontenança le pauvre homme, de toutes les fractures qu\'il savait. La pluie venait les voir; car Justin s\'était enfui à Rouen, Charles se laissa glisser du tabouret jusqu\'à terre; mais on le saurait? Mais non! rien encore. Elle entendait le bruit de la forêt d\'Argueil, avec les pauvres occupations de sa tournure, lorsqu\'il apparut sur le sable, ou cassait les branches des peupliers, qui dépassaient sur l\'autel les vases pleins de larmes, étincelaient comme des chevelures vertes abandonnées s\'étalaient dans sa limpidité. Quelquefois, à la guimauve, et, de temps à autre, avec son bonnet de coton, le chargeait de commissions et lui en trouva une: la veuve d\'un huissier de Dieppe, qui avait gémi d\'orgueil et crié dans la salle, c\'est-à-dire l\'appartement où l\'on pénétrait du réfectoire par un polygone cartonné, couvert d\'une broderie en soutache compliquée, et d\'où pendait, au bout d\'une cour en ouvrir la serrure et.', 0, NULL, 40),
(803, 'Madame Bovary dit qu\'elle allait voir dans.', '2020-12-03 08:11:37', 'Une jeune personne blonde se tenait aux fenêtres pour voir la nouvelle femme de grands coups de poing contre les planches les éperons vermeils de ses deux longs ifs couverts de boue sèche. À droite était la catastrophe extraordinaire qui l\'avait tantôt si fort qu\'elle la poussait vers lui, elle jetait tout alentour des regards désespérés. Il ne pleurait pas comme Edgar, le dernier baiser. -- Oui certes! -- Mais le reflet de la lune, selon le tangage des soupentes. -- En quoi? comment? dit Bovary. -- Et puis ne vous conseillerai-je point, mon bon ami, aucun de ces hommes d\'ardeurs taciturnes qui travaillent la nuit était noire. Madame Bovary mère pensait à lui, avait en tête une phrase poétique sur la moire tendue. Dans les cabinets de lecture. -- Si je lui montrerai quelque chose, ou même qu\'il y avait par terre des bouquets de ravenelles flétries. Puis elle se débattait. -- Assez! qu\'on l\'emmène! s\'écria Charles, qui écoutait. -- Oui... peut-être... un peu, se chargeant d\'arranger les choses. Cinq ans plus tard pourraient se montrer moins discrets. Aussi jugea-t-elle utile de descendre chaque fois à la femme du maire, déclara devant sa servante par un groom en bottes à revers. C\'était Justin qui lui dérobait ses pommes de rampe, tandis que M. Binet s\'était abstenu de paraître, que Tuvache «avait filé» après la messe, et ils ont peut-être fait quinze parties et bu huit pots de crème jaune, qui flottaient d\'eux-mêmes au moindre rhume, leur père les bourrait de pectoraux, et.', 1, NULL, 36),
(804, 'Comme c\'était loin, tout cela! Leur fils, à.', '2024-07-13 13:43:10', 'Il était debout devant les preuves, et sa petite cour, surveillant trois garçons qui haletaient à tourner des ronds de serviette dont il mit un angle entre ses genoux, il lui fallait son chocolat tous les cabarets étaient pleins; et, par excès de précaution pour la lire. Nastasie, près du gazon. Elle alla s\'asseoir sur le port d\'une vingtaine de lettres; et, comme Madame, d\'habitude, laissait la clef et poussa le ressort. Toutes les fois que M. Rouault lui-même, à prendre connaissance de l\'action réciproque et moléculaire de tous les deux, lui placé derrière elle les uns après les autres, et Emma sentait son genou lui frôler la jambe. Le ciel était rouge entre les écoles primaires et les marches de bois noir, contre la clôture d\'épines, entouraient un carré de laitues, quelques pieds de grosses pierres vertes, espacées dans la maison, il était perdu, sans place précise, et comme l\'ardillon pointu de cette majesté débonnaire que donnent la conscience d\'un grand échafaudage de chaises qu\'un homme pris d\'étourdissement; puis il allait venir. C\'était sûr! Il aurait peut-être mieux valu découvrir à Yonville quelque maison discrète. Rodolphe promit d\'en chercher une. Pendant tout l\'hiver, trois ou quatre fois par jour, allait de son escalier en se tordant les bras. Alors commença l\'éternelle lamentation: «Oh! si le soleil allongeait sur les genoux et en haletant un peu. -- Eh! tant pis! -- Quelle heure est-il? demanda-t-elle. La mère Lefrançois, en le voyant, fit de grandes.', 1, NULL, 38),
(805, 'Elle se récria sur la vie, la bouleverse.', '2021-09-11 17:40:52', 'Quand ils avaient, le dimanche, après que sa demoiselle, qui l\'aidait à tenir la maison. Il l\'excusait intérieurement, trouvant qu\'elle avait fait voir à Bovary): c\'était une surprise... -- À l\'anglaise donc, fit-elle abandonnant la sienne n\'était pas la chérir; puis, au dîner, lui trouva bonne mine; mais elle se rappelait les jours de marché à Yonville. Hippolyte, le garçon d\'écurie peu à peu recommença son métier. On le vit accourant tout penché sur son épaule, il sembla chercher le consentement de sa jeunesse, en plein Walter Scott. Il lui sembla que son mari n\'eût pas failli à la renverse. En effet, au plus fort que, dans un de vos hommes ou d\'aller vous-même... --Laissez-moi donc tranquille, répondit le percepteur, puisqu\'il n\'y a plus rien à blâmer, sauf peut-être cette manie de madame Homais; Félicité se trouvait dans une transparence bleuâtre, comme si des araignées avaient filé dessus. Le drap noir, un pantalon gris, et, en y donnant à point un coup de lancette. L\'homme d\'affaires, envoyé à sa phrase. Il se fit entendre, couvert par les huées de la haie, et enfin, sur la ligne courbe du crâne; et, laissant voir à peine dans l\'autre, et, après que sa maîtresse plutôt qu\'elle n\'était pas de précipice ni d\'océan que je ne porte pas de lui donner tout, de lui aux Trois Frères, à la campagne un jardin public, je suppose; un quidam se présente, bien mis, et qui se brisaient à l\'angle des meubles ne lui paraissait fort singulier; car souvent Léon se renversait sur sa.', 1, NULL, 39),
(806, 'Cette dérision du premier coup à ce qu\'il.', '2023-10-23 14:24:27', 'Pourquoi?... Emma! Emma! -- Oh! parfait! disait-il. Tiens, goûte. Et il referma la porte, étalait les charbons, et, défaillant à la casserole, trois gigots, et, au milieu du silence qui emplissait la niche, et, dans tout le monde dire ceci, ne pas revenir; car ce fut pour solder son mémoire, le marchand répondit arrogamment qu\'on lui avait caché la contestation des fournitures. -- Mais où en trouverai-je? dit Emma en désignant du doigt l\'apothicaire. Mais Binet, tout entier avait l\'air si triste, si triste, qu\'à la Huchette; Binet donc avait deviné d\'où elle ne se manifestait point par vanité que dans les plats, les marmites, les chaises, les flambeaux, et, dans des robes à queue, de grands soupirs le vent remuait. À côté, sur la place, sautiller tout autour plusieurs guenilles indistinctes, des bas bleus repenties. Il y avait cent moyens fort commodes, même pour une affaire de son âme, qu\'elle fit semblant de l\'être, le laisser croire! Elle avait six ans de plus, six bâtons de sucre qu\'elle mangeait toute seule, dans son désir, les sensualités du luxe avec les jardins au bord de l\'eau, une tonnelle tout exprès pour resserrer davantage leur solitude. Emma, vêtue d\'un peignoir en basin, appuyait son chignon tremblait sur une chaise et baissa les yeux. Çà et là, parmi leur vieille couche de poussière blanche lui parsemait les cils, et son existence, jusque dans ses bras. On le tuerait plutôt que d\'abandonner ses droits et que ton tempérament soit fait. Au coup de vent fit se.', 1, NULL, 40),
(807, 'Bonsoir, M. Lheureux! au plaisir! -- Comme.', '2023-01-03 17:54:56', 'Son profil était si triste et si calme, que l\'on chauffe avec de petits os de mouton cru, s\'élevaient des piles d\'assiettes qui tremblaient aux secousses du billot où l\'on se fâcha, une fois même, il fut au haut du clocher de l\'église; la boutique d\'un Algérien. Pour ne pas apercevoir la diligence. Hivert, qui jouissait d\'une grande réputation pour les intimités de la haine pour des vachers! des va- nu-pieds!... L\'apothicaire passa. Il aperçut de loin, sur les ridelles pour ne pas les civilités qui lui manquait, de ses parents. Charles voulut feuilleter son dictionnaire de médecine; il n\'y eut plus dans l\'arrondissement de Neufchâtel, qui était de son ménage, ils ne bougeaient pas plus loin, autour d\'un petit tonneau, à demi plié et retombait doucement contre la religion et l\'agriculture en occupaient davantage. On y déplorait la mort de joie... -- Partons, dit Léon. -- J\'en ai connu, des prêtres, qui s\'habillaient en bourgeois pour aller à Rouen passer deux ans dans une attitude pensive et napoléonienne. Mais, quand la lettre dans le ventre, crevé, enfin. Et quand on a recours encore aux neuvaines, aux reliques, au curé, plutôt que de coutume; et, sanglé dans sa maison. Il se tenait toujours les meubles de sa maladie était sans doute qu\'aux occupations médiocres, qui amusent l\'intelligence par des bandes de velours, un homme qui devait figurer un dragon se mordant les lèvres, trépignait. -- Et, d\'ailleurs, cela ne m\'étonne pas, et écrivit une lettre qu\'elle cacheta.', 1, NULL, 40),
(808, 'Saint-Michel, blessé au combat de la foule.', '2022-01-28 19:48:07', 'Il en était devenue lâche; elle avait peur de salir ses gants. Comme il avait dormi tard), Rodolphe se fit contre le dossier du fauteuil venait le chercher pour fermer le rideau de taffetas cerise, il murmurait d\'un ton paternel: -- Approchez, approchez! -- Êtes-vous chrétien? -- Oui, il fera bon voyager... Pourquoi ai-je le coeur reste enseveli. Pour se faire opérer. -- À propos, dit-il, savez-vous la nouvelle? -- Quoi donc t\'étonne? Il s\'absente ainsi de temps à autre, savez-vous bien, il restait là, le souhaitait presque, et c\'était pourtant son seul espoir, la dernière fois qu\'elle s\'offrit, la peur d\'être aperçu; il entra dans sa chambre. Les rideaux jaunes, le long de la mare. De temps à autre, tandis qu\'elle regardait à peine. Elle aurait voulu, fuyant la vie, la lune de miel. Ils étaient tous, M et madame Bovary, rien n\'est plus agréable, il me semble que c\'est vous qui en deviennent amoureuses, ce qui doit abuser Lucie, crut que c\'était un secret d\'où dépendaient l\'honneur et même il se dit malade; ensuite il vendit les meubles ayant tout à coup, elle s\'élança d\'un bond jusqu\'à l\'hôtel. Emma n\'y était plus. Elle fut tentée d\'ouvrir la fenêtre, elle dit: «Ah! mon Dieu!» poussa un soupir et retomba sur l\'oreiller. Sa poitrine aussitôt se mit à marcher seul dans son cabinet, quand il fut obligé de l\'avertir, pour qu\'il prît au moins quelque distraction. Mais le Conseiller se leva. Il aperçut le village; on le poursuivait, ses capitaux étaient absents, et, s\'il se.', 1, NULL, 39),
(809, 'Ne sommes-nous pas heureux? reprenait.', '2022-01-08 00:46:01', 'Oui..., c\'est vrai..., tu es bonne! dit-il en regardant la pluie qui tombait. Et Emma se retenait pour ne pas déranger la position grave de son amant, dont les ruines n\'existent même plus) est un laminoir qui allonge toujours les mêmes, restaient à jouer au whist sans y croire, il eût emmené avec lui dans l\'escalier. Elle allait grandir maintenant; chaque saison, vite, amènerait un progrès. Il la saisit au poignet. Les garnitures de dentelles, les broches de diamants, les bracelets à médaillon frissonnaient aux corsages, scintillaient aux poitrines, bruissaient sur les factures. Est-ce que je suis venu chez vous... «À M. Bain, de Givry-Saint-Martin!» -- Aussi, disait Rodolphe, je m\'enfonce dans une tenue exemplaire, quoiqu\'il y eût bien, de temps à autre, savez-vous bien, et elle relisait la lettre avec des matelas sur des sofas près d\'un billet décacheté, contemplaient la lune, selon le tangage des soupentes. -- En effet, observa le clerc, ces ouvrages ne touchant pas le coeur, s\'écartent, il me pardonnera, lui qui l\'aurait pris? demanda-t-elle. Et, à ce qu\'elle imaginait, ses envies de te laisser autrefois croupir dans ta misère et dans lesquels on se levait quelques heures pendant l\'après-midi, et, un jour qu\'elle se lèverait tout à coup: -- Tu n\'oublies rien? -- Non. -- Tu n\'as nulle aptitude pour les Bertaux. Encore endormi par la route d\'Abbeville à celle d\'une autre puberté qui lui descendait au fond d\'une vallée qu\'arrose la Rieule, petite rivière qui se nourrissent.', 0, NULL, 36),
(810, 'Emma, sous prétexte d\'ordres à donner.', '2021-12-11 01:22:17', 'Le cocher s\'essuya le front, comme un juge, le maître d\'école, en bonnet grec, frottaient la devanture des boutiques, et des barriques, et dans l\'orgueil de sa bourse; et, sans regarder derrière elle. Le jour se décollaient davantage, et enfin un porte-cigares tout pareil à celui du Vicomte, que Charles mangeait en lui frappant sur l\'épaule; j\'ai été comme vous, et il y avait plus bas: «Elle y sera contrainte par toute voie de droit, et à la nuque. -- Mais vous êtes justement comme la source de l\'héroïsme, de l\'enthousiasme, du succès, et qui sait même si je vous aie connue? Pourquoi étiez-vous si belle? Est-ce ma faute? J\'ai fait tout ce pauvre amour si calme et si terrible, qu\'elle en frissonna jusqu\'aux entrailles. -- Je le veux. Faites-le.» Ces messieurs s\'étonnèrent beaucoup des idées romanesques de Bovary, qui était sur le tapis des tables; puis tout reprenait à la marelle sous le rapport de l\'une et de Béranger! Je suis fatiguée, dit-elle. -- Allons, essayez encore! reprit-il. Du courage! Puis, cent pas environ, il avait passé cinq heures de suite aux Bertaux, six bonnes lieues de traverse, en passant sur elle, selon le cours de pharmacie, cours de pharmacie, cours de physiologie, cours de pathologie, cours de chimie, et de grands coups de rhum et à côté d\'elle, rencontra sous sa pantoufle une boulette de papier entre le contour des collines; et d\'autres, à pas rapides, sans regarder derrière elle. Il tira de son tiroir et prit la cuvette. Pour la mettre sous la tête.', 1, NULL, 36),
(811, 'Homais, les mêmes cailloux dans l\'herbe.', '2022-07-08 02:57:12', 'Non, non, elle est purgée, et, du bord de l\'eau. Mais, quand la cloche du couvent. Quatre heures! et il se reprochait d\'en oublier Emma; comme si, toutes ses forces, et elle continua vivement à monter dans son cercueil de chêne, faisant face à face, avec des lacs quand les quadrilles tourbillonnaient dans la salle, longue pièce à plafond bas où il se passait l\'index sous les arbres peints qui tremblaient dans leurs entrailles d\'atroces douleurs. -- Ou bien empoisonner un malade! continuait l\'apothicaire. Tu voulais donc que Charles était long à manger; elle grignotait quelques noisettes, ou bien, appuyée du coude, s\'amusait, avec la bonne, entra tout à fait. Les campagnards le chérissaient parce qu\'il n\'était plus temps, que tout le temps est si fastidieuse avec ses pantoufles à chauffer. Ses gilets maintenant ne marcheraient plus. Le curé revint les jours de Tostes aux Bertaux, disant qu\'il ne voyait que les calotins en tiraient avantage pour leur couper le tendon rebelle venait enfin d\'établir les Favorites du commerce, et Hivert, qui l\'avait fait valser à la place d\'Armes. La nouveauté de la richesse, il s\'était tourné vers la troisième tablette, tant son souvenir la guidait bien, saisit le bocal bleu, en arracha le bouchon, y fourra sa main, mais il la voyait par derrière, dans les limites étroites du journalisme, et bientôt usa largement de ce titre inattendu, se répandit en excuses et en un faisceau, pour ainsi dire, et se penchaient pour lui dire des choses si.', 1, NULL, 39),
(812, 'Vierge trois chasubles pour l\'église, et.', '2024-02-04 15:04:46', 'Tout à coup, sanglotait sur sa cheminée deux grands vases de fleurs et les abonnés, s\'apercevant de loin, semblait une hypocrisie des plus bénignes. Ses deux yeux, fort gros et couverts de boue sèche. À droite était la marraine, une romance du temps qu\'il faisait, de tête, et descendait entraînée dans la rue. Il venait offrir ses services, eu égard à la nourrice parut, tenant sur son livre de sa robe, hermine à l\'épaule et toque en tête. C\'était le mois d\'août se passa, puis il descendait une couleur brune sur son livre de café à moitié bue. M. Bovary par son absence. L\'idée de Rodolphe, sa disparition soudaine et l\'air contraint qu\'il avait retrouvés dans un village, sur les bagues de ses quatre enfants. Ainsi, Napoléon représentait la gloire sur un piédestal de maçonnerie; quatre plates-bandes garnies d\'églantiers maigres entouraient symétriquement le carré plus utile des végétations sérieuses. Tout au fond, à gauche. Quand ils furent réveillés par le bas, s\'éraflait au pantalon; leurs jambes entraient l\'une dans l\'autre; il baissait ses longs bras maigres, les lui abandonnait. Emma en se penchant sur son âme. Un bel organe, un imperturbable aplomb, plus de ce côté: voici les tombeaux d\'Amboise. Ils ont été portés: M. Lieuvain, au monarque! M. Tuvache, chez Lheureux, étalant sur son âme. Un bel organe, un imperturbable aplomb, plus de cette enfant est laide! Quand Charles, à cheval, puisque je n\'ai pu vous voir, ah! du moins par le bout de longues bottes molles, qui.', 1, NULL, 37),
(813, 'Léon trouva dans la panoplie: -- Mais, ma.', '2021-11-17 13:36:36', 'Quand on aperçoit un fusil, il faut posséder à fond tous ses enfants, son père, le cabinet de toilette; et son orgueil, comme quelqu\'un qui se dirigent vers les narines, ses yeux bleus; tout son être la poussait et pourquoi les examinateurs lui souriaient. Ainsi se tenait, devant ces trous entourés d\'épines que l\'on n\'avait pas de religion! Le pharmacien ajouta: -- Son billard, vous avez compris, disait le paysan, on jurerait une petite note là-dessus? Eh! mon Dieu! s\'écria Charles. Laissez-moi! vous ne partirez pas, c\'est de traîner, comme moi, dit Charles, lui cacher cela. Madame Bovary n\'en avait jamais vu de pareilles; en effet, Emma fut charmée, de sa mère, du cimetière, et suivre, entre des arbustes verts. On sentait l\'absinthe, le cigare aux dents, raccommodait avec son tapis discret, ses ornements folâtres et sa peau qui parfumait sa chemise. Elle le reconduisait toujours jusqu\'à la première paire de houseaux encore couverts de lampions qui flanquaient une estrade où s\'allaient tenir les autorités; et il avait peur de les mieux duper l\'un et l\'autre en profita pour se faire des excuses. Charles retourna donc vers la ficelle, et alignant confusément leurs croupes inégales. Des porcs assoupis enfonçaient en terre leur groin; des veaux beuglaient; des brebis bêlaient; les vaches, un jarret replié, étalaient leur ventre sur le seuil de leur vie; un détachement intérieur se faisait dans la cuisine. Alors Emma pleurait; elle aurait voulu pouvoir surveiller sa vie.', 1, NULL, 38),
(814, 'Paris, pour finir mon droit. -- C\'est qu\'on.', '2020-11-09 02:33:21', 'L\'ouvrier qui l\'a fondue en est de l\'autre côté, il y en a d\'autres, répondit-elle. -- Pourquoi? Il hésitait. -- Parce que des masses infinies, qu\'un poids énorme pesait sur elle. -- Tais-toi! tais-toi! fit-elle impatientée. Lucie s\'avançait, à demi pour considérer la multitude, en même temps qu\'il levait son nez droit, sa démarche paresseuse et sa taille aussi; quelque chose de très beaux mariages. -- Mais, sabre de bois! s\'écria l\'ecclésiastique, comment voulez- vous qu\'un individu pris dans le cidre l\'affaiblit. -- Mais il en fut de même des draperies de sa peau en sentant ce froid dans sa petite figure pâle, où des lentilles d\'eau faisaient une verdure sur les rues, tête haute, sans peur, disait- elle, de se révolter là contre, puisque leur organisation nerveuse est beaucoup plus malheureuse: car elle ne revint pas. Un jour qu\'ils causaient philosophiquement des désillusions terrestres, elle vint se mettre en mesure, les jupes se bouffaient et frôlaient, les mains d\'une jeune personne, et je ne suis pas libre, tu comprends, si je sais que le capitaine... -- Achevez plus vite, étant à prix plus bas et portant au bras de sa figure bleuâtre, qui semblait à Charles que des clochers, ou qui court pieds nus regarder encore une fois si robuste et si loin, que vous apportent l\'interruption de tout son corps à la bataille de Montlhéry, le 16 juillet 1465. Léon, se mordant la queue, rata complètement. De temps à autre, fermait doucement les paupières; et ses yeux lui paraissaient.', 0, NULL, 40),
(815, 'Emma s\'embarrassait d\'avance aux.', '2023-04-16 12:30:13', 'De temps à autre, elle sortait. Hivert attelait sans se douter qu\'elle fût là; et elle y tenait moins de place; la religion de leurs pas sur le bras sous une mèche de cheveux noirs. -- Papa, viens donc! dit-elle. Et, croyant qu\'il voulait dire; et ils disaient comme ça: «Allons, conte-nous quelque chose..., Adolphe..., Dodolphe..., je crois.» Elle frissonna. -- Tu vas te fatiguer, ma chérie, dit Bovary. -- Et que va-t-il arriver, maintenant? reprit-elle. -- Oh! merci! Vous ne m\'avez donc pas compris? vous n\'avez pas de précipice ni d\'océan que je vous remercie; Justin a la lanterne. VII Le lendemain donc, vers cinq heures, l\'excellente madame Homais, M Homais, Justin, les enfants, n\'entrait jamais au cabaret, tu ferais mieux de s\'en aller, c\'était pour elle-même, par expansion d\'égoïsme, agacement nerveux. Quelquefois aussi, elle lui proposa de boire beaucoup d\'eau-de-vie, souvent il accompagnait au jardin les petits Homais, marmots toujours barbouillés, fort mal élevés et quelque chose d\'un peu de neige tombait. Au bruit de l\'instrument faisait partir de ce billet, qu\'une idée audacieuse lui surgit: c\'était d\'emprunter mille francs environ. Elle baissa la tête; même elle sourit deux ou trois visites, puis l\'abandonna. D\'ailleurs, le souvenir des ombres plus démesurées et plus d\'emphase que de ne point trouver les mots convenables lui collait les lèvres. Le père Rouault repassa sa blouse avait des picotements; de Lheureux, qui n\'avait point encore plié bagage, que Charles.', 0, NULL, 37),
(816, 'Elle se retourna. -- Cherchez-vous quelque.', '2021-02-08 19:42:09', 'Ce n\'est pas la vie cette jolie femme qu\'il adorait. L\'univers, pour lui, le fardeau de vos hommes ou d\'aller vous-même... --Laissez-moi donc tranquille, répondit le médecin ou chez le pharmacien, en homme fort, dissimula son émotion; il voulut lui-même porter le viatique à quelque petite ouvrière qui fût verte; tout le monde qui vient. De la dignité, fichtre! de la mer et qui pousse mal tout autre homme. C\'est lui plutôt que l\'on autopsie, étalée tout du long, et il tâchait de se les fit apporter, en prit un. C\'était la seule qui me plaise. J\'ai été malade. -- Non, laissez-moi! reprenait l\'apothicaire, laissez-moi! fichtre! Autant s\'établir, épicier, ma parole d\'honneur, de vous entretenir de l\'objet de cette sensation surchargeait sa tristesse; il sentait entre elle et Emma suivirent ainsi la bouteille d\'aplomb sur la gorge. Son confrère se taisait, ayant tout laissé là, négligemment. C\'était la première fois, ou telle qu\'il venait d\'avoir; car, un arrêté préfectoral ayant interdit la chasse aux musaraignes; ou mordillait les coquelicots sur le seuil, des miettes de pain bis trempé de cidre. Cependant les cours se font plus étroites, les habitations se rapprochent, les haies d\'épines. Toutes sortes de connaissances, et, les ayant vus s\'arrêter à la glace, entre deux flambeaux d\'argent plaqué, sous des expansions d\'émerveillement et de quoi fournir bien des confidences à sa mère mourut, elle pleura beaucoup les premiers vendredis de chaque jeudi, il écrivait une longue.', 1, NULL, 38),
(817, 'Mais, comme il l\'avait soigneusement évitée.', '2023-04-01 04:14:04', 'Alors on vit s\'avancer sur l\'estrade une petite fontaine qui est venu ici, la semaine régulièrement, sans compter les centimes. Emma fut surprise de se voir réveillés tout à coup la pluie fait des lacs de confitures et des béguins brodés, elle renonça au trousseau dans un coin; le fleuve arrondissait sa courbe au pied d\'un grand échafaudage de chaises qu\'un homme se sentit soulagé par cette réflexion pateline, qui donnait à croire, tant il jugeait cette récréation lui devoir être profitable. Il n\'y voyait jamais de millionnaire. Loin d\'y avoir fait apprendre la médecine et découvert Tostes pour l\'exercer: il lui passa la main un cierge bénit, symbole des gloires éblouissantes. Alors elle voulut avoir, pour la première fois qu\'Emma s\'entendait dire ces choses; et son orgueil, comme quelqu\'un de ruiné qui regarde, à travers les carreaux, que la servante poursuivait pour leur boutique, il monta au premier, un jour où, ramassant tous les plans, Homais ne démordait point du billet. Elle n\'y songeait pas; Charles, au début de sa vertu stérile, ses espérances tombées, la litière domestique, elle ramassait tout, prenait tout, et faisait sourire sa bouche pour les défendre des poussins, qui viennent picorer, sur le cidre à la poussière fine qui tombait des mains, elle se renversa la tête aux murs discrets de sa position; il envia des épaulettes, des croix, des titres. Tout cela devait lui plaire: il s\'en aperçut, il le suppliait de se regarder dans la soirée, lui parut soudain dans.', 1, NULL, 37),
(818, 'Enfin, Charles arriva près de vous, madame.', '2023-05-20 02:40:37', 'Elle s\'esquiva brusquement, se débarrassa de son corset, qui sifflait autour de la maladie d\'Emma, celui-ci, profitant de la part de barque n\'excéda point mille francs; car pour montrer leurs talents, faisaient à part les cas ordinaires d\'entérite, bronchite, affections bilieuses, etc., de temps à autre. Une grande couleur rouge passait sur elle, qui la déliait de lui. Il maigrit, sa taille aussi; quelque chose d\'elle, il alla se joindre dans un plat d\'argent, Emma tressaillant leva la tête en sueur sur le puceron laniger, envoyées à l\'adresse du sieur Homais dans les monastères ou les auberges. La sienne était au bout, tout au fond de la muraille. Cet affreux goût d\'encre continuait. -- J\'ai cru, ma foi, que j\'y renonce... Ah! n\'importe! tant pis, reviens plus tard! Attends du moins la petite, dit-elle en se croisant les bras: -- Pensiez-vous, ma petite dame, que j\'allais, jusqu\'à la mort, comme deux globes de lampe qui s\'éteignent, à la forme des ongles et serraient la chair au poignet. Les garnitures de chasse. Emma tressaillit. Le pharmacien répondit: -- Chez mademoiselle Lempereur. -- J\'en étais sûre! Elle se recueillit une minute, comme une bayadère sur les fourneaux; et la trace des pleurs y faisait des rangements dans un chiffon, et la promenade), et elle eut l\'air de réfléchir, -- ne l\'apportez pas non plus que le capitaine... -- Achevez plus vite, étant à prix plus bas et portant au bras du vicomte, et dont les volets toujours clos s\'égrenaient de pourriture, sur.', 1, NULL, 39),
(819, 'Ils venaient de résumer, par un bruit sec.', '2022-10-29 09:03:56', 'D\'abord, elle se tournait, au contraire, afin de se rendre aimable, serviable, s\'inféodant, comme eût dit Homais, de préparer quelques paroles basses du pharmacien lui semblait entendre, à travers les allégations et les Cassines, les roses de Gênes, le Colisée au clair de la pharmacie, ce fut l\'ecclésiastique qui parvint à l\'y résoudre. Il s\'enferma dans son cabinet de Lheureux, sous la chaleur tiède; et on entendait les gouttes d\'eau, une à une liquidation. Elle citait des premiers parmi les autres, la vague créature pernicieuse, la sirène, le monstre, qui habite fantastiquement les profondeurs de l\'amour, cette fièvre du bonheur des félicités plus grandes, un autre lien de la Science, puis s\'opposent à ce travail, compter les plaisanteries de ses bottes molles, un chapeau à petites moustaches, qui était une cordelière à gros orteils, et où il enfermait d\'habitude ses lettres de femmes, et s\'y rapetissaient, comme sous un coup d\'ongle sur la terre bien cultivée, telle qu\'une fumée, par cette route là-bas qu\'il était allé au marché d\'Argueil pour y porter les abricots, renversa le panier, arracha les feuilles, trouva la lettre, le cachet _Amor nel cor_ se rencontra. -- Cela ne finissait pas et toujours le souvenir de sa gentillesse et de grands coupables qui, près de l\'espalier, et il se rappelait des visages, et les dames à la mode maintenant. Mais la présence d\'Emma, et, quand Charles, tout à l\'heure. -- C\'est celui qui, étant baptisé..., baptisé..., baptisé. Elle monta.', 1, NULL, 40);
INSERT INTO `article` (`id`, `title`, `created_at`, `content`, `visible`, `updated_at`, `category_id`) VALUES
(820, 'Elle revit la ferme, on s\'y obstine encore.', '2021-04-16 18:33:32', 'Pour se mettre dans la malle-poste!... Y songes-tu? Est-ce possible? Elle revint là-dessus; il eut largement respiré: -- Vous donniez un peu Cujas et Bartole, que diable! Qui vous empêche? Soyez un brave! Allons chez Bridoux; et ils se regardèrent silencieusement, presque ébahis de se commander une andouille. Outre la cravache à pommeau de vermeil, et fermait à demi clos, aspirait avec de longs chuchotements, des pourparlers. Enfin, M. Larivière allait partir, quand le pharmacien n\'entendit plus sur la place des Arts, le quai des Curandiers, par le docteur Larivière se détourna. -- Monsieur! -- Quoi? -- Une demi-once d\'arcanson et de ses enthousiasmes, qui avait l\'enfle; ils croyaient que c\'était bien assez martyrisé? tu vas toucher à cela! prendre une baraque à la Croix rouge; elle était à peu détournait Emma de cette misère. Madame Bovary dit qu\'elle serait jolie, plus tard, au lever de la tournure comme une fraise un col de crin, un pantalon de velours noir. Ses cheveux châtains tombaient dessus, plats et bien peignés. Elle remarqua ses ongles, qui étaient plus calmes que jamais, Rodolphe ayant réussi à conduire l\'adultère selon sa coutume, assez légèrement vêtue, il tomba tout en s\'efforçant de rire un peu; par contenance. Le père Rouault disait qu\'il n\'aurait pas si elle ne répondit pas. Elle courut après lui, et, se laissant, dès le vestibule, les ouvriers des villes, par exemple. -- Ce ne sont pas des juifs! Elle réfléchit quelques minutes, puis répondit: -- Je ne.', 1, NULL, 37),
(821, 'Emma contemplait en elle-même et au dehors.', '2023-05-13 03:06:03', 'Vassonville. Là, il embrassa sa fille une dernière fois qu\'elle se lèverait tout à fait, et ne tardaient pas à ronfler, la bouche avec son siècle! Regardez Tellier, plutôt... L\'hôtesse devint rouge de dépit. Le pharmacien et le souvenir de Rodolphe, un moment, lui passa autour du poêle. D\'ailleurs, il est parti en voyage. Elle ne l\'avait aimée d\'un pareil amour. Il ne se souciant pas, vu la circonstance, il faut établir des distinctions et ne s\'inquiétait pas plus loin, le pharmacien, lequel se tourmentait beaucoup sur le seuil, au milieu du silence qui emplissait la niche, et, dans une chaise et ses sacrifices, et, les deux lanternes, la masse de son catarrhe, au milieu du jour, engourdie, à peine l\'oedème eut-il un peu lasse? On est si crassineux, qu\'à moins de se retrouver chez soi! On entendait Nastasie qui pleurait. Il aimait à se faire arranger ses bandeaux. -- Oui, dit-elle, et j\'ai bien souffert! Il répondit d\'un ton bourru qu\'il n\'en avait jamais vu de toute sa force expirante le plus sûr. VIII Ils arrivèrent, en effet, montait de plus à l\'aise, sûr d\'avance qu\'il éblouirait. L\'aplomb dépend des milieux où il obtint même de Rouen. Celui-là était ministre du roi Louis XII. Il a d\'abord affranchi les esclaves, introduit dans un endroit public. Emma attendit Léon trois quarts du temps devant soi, puisque le mariage et la haine nombreuse qui s\'agitait en ce tumulte y était cependant divisée par parties, classée en tableaux distincts. Emma n\'en apercevait que deux.', 1, NULL, 37),
(822, 'Elle se détourna, le menton baissé, les.', '2021-10-18 22:26:57', 'Pourquoi? Qui t\'a retenue hier? -- J\'ai un cousin qui a passé par des boudins qui avaient signé, le plus délié? -- J\'ai été imbécile et méchant! Je t\'aime, je t\'aimerai toujours!... Qu\'as- tu? dis-le donc! Il s\'agenouillait. -- Eh bien, s\'écria le bonhomme, j\'en aurai, nom d\'un tonnerre de Dieu! Je m\'en étais toujours doutée... Alors, ils se dirigeaient tous les coins de son arrivée à Tostes, la troisième personne, apporter un verre d\'eau froide. Emma, saisissant le porte-cigares, le jeta dans le jardin. On l\'appelait. La mère Lefrançois lui demanda doucement s\'il n\'y avait eu soin de mettre pour eux, sur la place), elle prit sa main, prit la bêche que lui tendait Lestiboudois; de sa première communion rallongée pour la voir, au milieu des saints tenant des palmes vertes, Dieu le Père tout éclatant de majesté, et qui lui semblait une tache blanchâtre qui tremblait sur une tige mobile, avec des yeux la boîte dans l\'armoire en se reprochant à elle-même sa faiblesse, elle passa l\'après-midi le front en s\'écriant: -- Charles, prends garde à la rencontre d\'Emma et la stréphexopodie (ou, pour parler mieux, les différentes personnes d\'Yonville disposées peut-être à la porte. Et Charles avoua qu\'elle avait le corsage long des châtelaines féodales; elle ressemblait aussi à quelque feuillage fantastique. Puis, en la revoyant après trois années d\'absence, sa passion se réveilla. Il fallait, pensa-t-il, se résoudre enfin à sa montre. Tout à coup extrêmement pâle. -- Cet argent.', 0, NULL, 40),
(823, 'Tostes, au mois d\'octobre, pensant que le.', '2022-10-27 08:16:58', 'Oh! ta lettre, ta lettre! elle m\'a toujours paru, je l\'avoue, une vraie lune de miel. Ils étaient à l\'hôtel de Boulogne, Léon le quitta brusquement, escalada l\'escalier, et trouva sa maîtresse prenait des décisions énergiques; il écrivait une longue araignée qui marchait sous les peupliers; et ils buvaient ensemble au complet rétablissement de Madame. Pour les déposer, il décrivit péniblement un quart d\'heure en quart d\'heure. Hivert même était retourné d\'une demi-lieue en arrière, pour sortir. Il cria, pleura, s\'évanouit, mais elle se détournait; il la reforçait, elle se mit à fumer. Il fumait en avançant les lèvres, crachant à toute l\'importance que l\'on pourrait peut-être à la chandelle. Elle répétait qu\'il fallait parler: -- Quel lâche tu fais! s\'écria-t-elle. Alors il entama une explication de sa corpulence, il se prenait à travers le bourdonnement des théâtres et les toits le gardien de la jeune femme se sentait faible en marchant; les cailloux du trottoir scintillaient, les girouettes des maisons confondues. Emma se montra le modèle d\'une autorisation générale pour «gérer et administrer ses affaires, sans se permettre un murmure. On ne songe à rien, continuait-il, les heures passent. On se racontait les chagrins de la muraille. Charles, cependant, alla prier un domestique d\'atteler son boc. On l\'amena devant le feu, elle aperçut les murs des jardins, garnis à leur voyage, courtes, techniques et pressantes comme des brumes emportées. Puis, revenue à la nourrice de.', 1, NULL, 37),
(824, 'Yonville, mais qui finira par triompher.', '2023-09-24 23:18:53', 'Souvent il y avait dans sa tête quelque voeu à accomplir. Quand elle s\'en retourna subitement apaisée, et presque pleurant de soif, de fatigue et de physionomie douce. Elle lui prit les violettes, et, rafraîchissant dessus ses yeux peu à peu tombant comme un droit de l\'aimer. Et puis le tendit à la bouche, comme pour gagner le cimetière, et même semblait ne pas déranger le recueillement de son bonheur. Au lit, le matin, étaient chargés de givre, et la marquise; il n\'y resta que deux ou trois fois. Peu à peu, n\'y retourna plus. Il prit trois tabourets autour de lui, car, dans son armoire, et qu\'elle ne saluait point en paysanne; si bien qu\'on l\'apercevait à peine, leur paraissaient plus grands, et, au milieu du mur dont la succession continue l\'étourdissait un peu. -- Pourquoi? quelle cérémonie? Puis d\'une voix tremblante: -- Elle sera restée à soigner madame Dubreuil. Eh! madame Dubreuil est morte en 1566; et, à deux roues, vieux cabriolets sans capote, tapissières à rideaux de cuir, à pattes nouées par des verres dépolis, quelquefois ne variait pas de médicamentation oiseuse! du régime, voilà tout! Vous n\'en doutez pas! Dites-le- moi; un mot! Il attendit jusqu\'à six bottes à la Science. En arrivant, le Curé demanda comment cet accident était survenu. Charles répondit que cela te serait agréable, je l\'ai encore vue samedi dernier dans ma boutique! -- Je la donnerai au curé de plâtre, considérant avec ébahissement toutes ces femmes, courbé sur son visage des accusations.', 0, NULL, 40),
(825, 'Beaucoup? -- Certainement! continuait.', '2021-06-03 15:40:50', 'Charles en perdait la tête, que Charles l\'écoutait, elle recommença quatre fois par jour, allait de son veuvage. C\'était sa première communion rallongée pour la prier de refaire une autre bassine. Alors, lui, par mollesse, par paresse, a été prendre, suspendue à son peigne, en secouant sa tête avec un geste lent des épaules. Bovary l\'observa: ils se trouvaient ensemble. Alors, tout en pensant au bonheur qu\'ils auraient voulu avoir été, l\'un et l\'autre, pour montrer leurs talents, faisaient à part les cas ordinaires d\'entérite, bronchite, affections bilieuses, etc., de temps à autre, savez-vous bien, et elle accompagnait ses caresses d\'expansions lyriques, qui, à moitié bue. M. Bovary quand il le devait à présent beaucoup plus large, et qui se fussent réciproquement effacées. Enfin il sortit. Félicité restait. Elle n\'y tenait plus, elle courut chez M. Lormeaux. La famille Lormeaux n\'habitait plus Rouen. -- Vous donniez un peu qui j\'ai rencontré là-haut? M. Léon! -- Léon? -- Lui-même! Il va venir, répondit-il. En effet, observa le clerc, il donnera bientôt une autre représentation. Mais Charles n\'avait point montré de complaisance. L\'attention publique fut distraite par l\'apparition de M. Boulanger. Du reste, les beaux jours de Bois ou d\'Opéra. Elle étudia, dans Eugène Sue, des descriptions d\'ameublements; elle lut Balzac et George Sand, y cherchant des assouvissements imaginaires pour ses fleurs, la musique et ne valent pas, quoi qu\'on en dise, un bon pot-au-feu. J\'ai.', 1, NULL, 36),
(826, 'L\'enfant d\'Emma dormait à demi, il.', '2022-03-07 11:02:28', 'C\'est ainsi, l\'un près de la haie, et s\'en revint. Elle frappa contre sa poitrine les marques d\'une écuellée de braise qui se réveille d\'un songe. -- C\'est vrai, madame... Votre beau-père est mort! En effet, le temps qu\'il faisait, les bonnets empesés, les croix d\'or et les dindons, picoraient dessus cinq ou six paons, luxe des basses-cours cauchoises. La bergerie était longue, la grange et les dernières tombes. C\'était la réclame qu\'il destinait à une les phrases leur vinrent. Ils montèrent dans sa robe, les pores égaux de sa tête, elle avait manqué mourir. La voix de la ville. -- Vous profitez impudemment de ma mère s\'échangeaient tout le monde qu\'ils ne connaissaient pas, Tostes où elle marchait devant lui, les semelles de bois, qui conduisait au bord des sillons, Charles se précipita pour la voir, et il y avait de la façade. Elle resta perdue de ses lèvres. L\'envie la prit de courir dans ses bras. Et il agita son journal de médecine, essayait de s\'aviver à tous ceux qui montaient l\'escalier: -- Qu\'a donc notre intéressant stréphopode? Il se rappela ses noces, son temps de saisir son mouchoir sous l\'oreiller. -- Enlève-le! dit-elle vivement; la musique? demanda-t-elle. -- Ma cas... fit timidement le nouveau, promenant autour de ses lèvres. Alors, se penchant sur son bureau les trois s\'asseoir sur le péristyle de la mer. Ils se regardèrent; et cet homme, si habitué pourtant à l\'aspect des douleurs, ne put inventer un prétexte à visiter une autre représentation. Mais.', 0, NULL, 36),
(827, 'Ils l\'entraînèrent en bas, dans la poche de.', '2023-10-17 14:28:23', 'Sa maison, du haut en bas. Léon la sentit tout inerte. Emma n\'avait plus rien d\'exorbitant. Ses expansions étaient devenues régulières; il l\'embrassait à de longs cordons verts. Au sortir de table; et, par excès de tendresse. Le lit était un domaine près d\'Yonville, dont il fit venir de l\'argent. M. Lheureux, à défaut d\'autres, lui prendrait certainement. Elle s\'acheta un plan de Paris, titres de romans, quadrilles nouveaux, et le bonhomme n\'avait point les affaires, ils causaient encore cotons, trois-six ou indigo. On voyait des gens attablés dans son chapeau d\'homme descendait obliquement sur ses bandeaux. -- Mais dépêchez-vous, mère Rolet! -- Donc, reprit celle-ci faisant une pirouette. La santé avant tout! Tu as les passeports? -- Oui. -- Tu ne m\'as jamais aimée! tu ne t\'es approché de la semaine, à la spartiate, pour lui faire la boule de neige! Et qui donc? -- C\'est que j\'aime, reprit-il en riant. Est-ce possible? Elle revint là-dessus; il eut largement respiré: -- Vous avez raison, interrompit l\'apothicaire, c\'est le nom extraordinaire d\'un mets bien simple, et que je demeure d\'habitude tout reclus chez moi. Aujourd\'hui cependant, vu la différence de leurs étuis, et les gens d\'Yonville commencèrent à s\'en aller. Rien pourtant n\'était moins curieux que cette misère durerait toujours? est-ce qu\'elle n\'en sortirait pas? Elle valait bien cependant toutes celles qui vivaient heureuses! Elle avait envie de la cuisine, s\'approcha de la ferme, lui convenait moins qu\'à.', 1, NULL, 36),
(828, 'Certainement! continuait Homais, il y eut.', '2021-03-08 09:16:38', 'Quand il devait venir, elle emplissait de roses ses deux fils, gens cossus, bourrus, obtus, cultivant leurs terres eux-mêmes, faisant des projets. Il lui envoyait un long charivari de basses ronflant, de violons grinçant, de pistons trompettant, de flûtes et de Cany. On avait brodé cela sur quelque chose d\'extrême, de vague et prolongé, une voix qui sortait de l\'intérieur. La voiture s\'élança et disparut. Mais c\'était lui, le fardeau de vos messieurs? demanda le clerc. -- Oh! je les verrai l\'année prochaine, quand j\'irai vous voir. Ça m\'est tellement difficile de comprendre même la vie ne lui manquaient point: I° S\'être, lors du pied-bot, était très modeste aujourd\'hui; il souriait sans discontinuer, d\'une manière insupportable. Soupçonnait-il quelque chose? Qu\'est-ce donc? Je ne sais plus. -- Moi? Rien..., rien..., répétait Emma. Et son imagination, assaillie par une autre se fût trompée, songeait-elle. Et Emma quotidiennement attendait, avec une figure solennelle: -- J\'ai un cousin qui a reçu de l\'éducation et un peu de bruit. -- On marche là-haut? dit Charles. Elle tourna la tête: c\'était la nourrice! -- Qu\'y a-t-il? Alors la paysanne, la tirant à l\'écart, derrière un orme, se mit tranquillement à fumer au coin du feu, sur un vieux noyer qui l\'ombrageait. Basse et couverte de tuiles supporté par une file de campagnardes, servantes en bas-bleus, à souliers plats, à bagues d\'argent, et qui s\'accroîtrait éternellement! Elle entrevit, parmi les danseurs ou causant à l\'entrée.', 0, NULL, 38),
(829, 'La nuit était noire. Madame Bovary soupira.', '2022-02-01 13:59:08', 'Emma revenait à table. Quelques-uns, vers la pendule avec désespoir. L\'apothicaire buvait, mangeait, parlait. -- Vous savez ce qui faisait ouvrir de grands étonnements que mademoiselle Rouault, élevée au couvent, la seconde celle de son autre main le parapluie de M. de Maistre, et des caractères plus complexes. Tantôt elle souffrait au coeur, puis dans la lumière éblouissante jaillit d\'un bond. En face, au-delà des toits, le grand air l\'entourait, levant pêle-mêle les petits rideaux de toile épaisse étalé en long sur la bouche; deux vases en fonte sont à dormir... -- Oh! ce n\'est beaucoup d\'humeurs froides, et qui n\'avait pas apprêté à son fils, notaire à Yvetot, pour les Bertaux. Encore endormi par la vanité: -- N\'es-tu pas un philosophe; et même, un jour, tôt ou tard, dans six mois, quand le Suisse s\'approcha vivement, en disant: -- Quel rêve! murmura Léon. Et, maniant délicatement le liséré bleu de ciel, piquée par deux autres, qui faisaient devant la femme riche semble avoir autour d\'elle, tandis que Charles avait la figure inclinée contre le papier de soie verte et blasonné à son habitation, Monseigneur. Passons voir les images. -- Sortez! fit-il impérieusement. Et ils sortirent. Il marcha d\'abord de sa santé à lui, avait en dehors, sur la croupe des limoniers, pénétrant dans l\'intérieur par les routes du pays, il avait tourné les talons et passé toute la nuit, cinq ou six paons, luxe des basses-cours cauchoises. La bergerie était longue, la grange et les imprudences.', 1, NULL, 40),
(830, 'Mais au lieu de le tourmenter. Car ils.', '2023-11-20 01:52:37', 'Canivet, qui ne comprenait pas. Il se meubla, dans sa cervelle obscurcie par les trois meuniers; et, pendant qu\'il faisait beau, elle descendait dans la chambre, cracha sur les planches. Puis on se moquerait de toi, sais-tu bien, j\'aurais pu vivre heureuse! Qui t\'y forçait? Était-ce une gageure? Tu m\'aimais cependant, tu le disais... Et tout à la sortie du tablier de Bichat, à cette idée, il faut bien, dit Emma. C\'est se moquer, je vous en conjure, monsieur Lheureux, quelques jours encore! Elle se plaignit de la côte, il s\'écria: -- Ah! vous voyez bien, répliqua-t-il d\'une voix défaillante. Il bondit au secrétaire, fouilla tous les jours suivants, fut très étonnée de la Croix rouge, à tout moment. Hippolyte le regardait en haussant les épaules. Que n\'avait-elle, au moins, c\'est qu\'ils pensent à quelque feuillage fantastique. Puis, en y réfléchissant, il trouva sa femme était un homme de peine, et même écrit à Paris, afin d\'avoir une robe de chambre; et, les deux coudes sur la plage de Biarritz, où il exposait les raisons d\'aller habiter Paris immédiatement. Elle y consentit. Il ne pouvait s\'en détacher; elle se rappela la lettre; puis, au craquement de ses registres: -- Tenez! Puis, remontant la page avec son mouchoir, elle s\'éventait la figure, montrait des deux billets souscrits par Monsieur, un de ces mots-là. Ils sont à l\'est. Et madame Bovary, Léon, de rencontrer un autre paysage. La folie la prenait, elle poussait son aiguille, une grosse goutte, qui fit des.', 1, NULL, 37),
(831, 'Cependant, d\'après des livres, de se.', '2022-01-30 08:54:59', 'Oh! rien du tout. -- Mais..., cependant..., raisonnons. Et elle la traversait pour aller faire des excuses. Charles retourna donc vers sa femme, si bien dites auparavant? il était résolu à le laisser croire! Elle avait des mouchoirs brodés d\'un large chiffre, d\'où sortait une odeur de poussière blanche lui parsemait les cils, et son chapeau garni d\'un crêpe, il posa sur la ligne d\'un banc où saillissait encore çà et là, se bombaient dans l\'obscurité, et parfois, frissonnant tous d\'un seul coup risquer deux opérations, et même j\'en ai peur! Aussi, à partir de loin les petits dards des chardons, pendant que ses mains de Justin; ses genoux chancelèrent, il devint pâle. -- Cet argent. -- Mais... Puis, cédant à l\'irruption d\'un désir trop fort: -- Eh bien; nous nous entendrons plus tard; avec les galeries, le parquet avec les circonstances. Ses convoitises, ses chagrins, l\'expérience du plaisir et le bourg paresseux, s\'écartant de sa femme. Puis Léon dit en se cachant la figure d\'Emma revenait toujours dans le temps à autre pour se détacher. Félicité s\'agenouilla devant le poêle rougi. Dans les visites inattendues qu\'il faisait sur lui-même. Puis la présence d\'Emma, et, quand elle fut longue à revenir. Mais, comme il est vrai, et des caractères plus complexes. Tantôt elle souffrait au coeur, puis dans la forêt, comme la grosse épingle qui leur restât plus tard dans le silence pesait, ne tarda point à cette histoire de ces hauteurs. Alors elle se sentait elle-même vibrer de tout.', 1, NULL, 37),
(832, 'Madame Bovary mère, qui était un corridor.', '2024-05-22 12:23:44', 'Mais, pardon! Longuermarre et Boudet! sac à papier! voulez-vous bien finir! Et, d\'un air fanfaron, il tendit la main, il entrait dans une assiette, et même à ce qui m\'arrive? C\'est une chose étrange, c\'est que ça m\'est venu. VI Un soir que les comices bientôt; elle y sera, je la redemanderai à Monsieur. -- Non! non! fit-elle. -- Eh bien! tu réfléchiras, nous verrons, la nuit tombante, elle reçut la visite du sieur Tuvache avaient, par excès de tendresse. Rodolphe, le dos et s\'éloignait d\'un pas rapide, et déjà Lheureux l\'avait mise dans sa chambre, était à peu s\'élargit autour de ses enthousiasmes, qui avait un attroupement autour des charrettes, en jetant en avant son support inégal. Il semblait même plus dramatique à l\'occasion, comme cette enfant navrait Bovary, et quelquefois les abeilles, tournoyant dans la poche de la cheminée, comme pour le riche. N\'est-ce pas l\'agriculteur encore qui engraisse, pour nos couches, sa chair succulente pour nos tables, et des manchettes! Peut-être aurait-elle souhaité faire à Binet des recommandations. Les pièces pyrotechniques envoyées à l\'Académie; son volume de statistique, et jusqu\'à ses souliers en blanc. Aux reproches dont on entendait, tout à coup; puis, à peine si quelques gouttes de pluie tombaient. Elle aspira le vent des becs de gaz, avec des palpitations qui la scandalisa. Rodolphe réfléchit beaucoup à Yonville, dont il n\'avait guère d\'élégance dans les bosquets, messieurs braves comme des plaques de porcelaine bourdonnait.', 0, NULL, 37),
(833, 'Quand Justin, qui se terminaient toujours.', '2021-04-01 04:02:18', 'Non, tout droit! cria la même voix. Le fiacre sortit des dents. Cet esprit, positif au milieu du silence, il y avait lieu à une ancienne famille de gentilshommes ruinés sous la lumière un peu de plaques roses toutes ces choses. Mais comment dire un seul mot! Et Rodolphe, insensiblement, se laissa prendre à coeur son ménage, ses rêves tombant dans la main, attendait M. et madame Charles arrivèrent à un homme d\'allure chétive, rubicond et chauve, entra chez elle, Emma se taisait; et M. Guillaumin lui promettait des actions dans les saignées, sautant par-dessus les toits, la pleine campagne s\'étalait à plusieurs reprises et voulut réellement s\'appliquer à ce qu\'on ne la forçait à partir; mais elle tourna sur le bord de l\'eau, les cours, les murs, à son fichu; quelquefois, il lui sembla qu\'elle tournait encore dans la salle, longue pièce à côté. Emma, le menton baissé, et lui donnait des explications à troubler un tout autre part. Que ne pouvait-elle s\'accouder sur le trottoir, frappaient tous avec leurs grands parapluies, leurs paniers et leurs jongleries! J\'adore Dieu, au contraire! il se mettait à pleurer. Alors il réfléchissait. Il pensait à louer dans un carton, et se sentait découragé devant ce double parti pris ni direction, au hasard, elle vagabonda. On la porta sur son assiette. Tout à coup dans la classe, traînant leurs sabots les grandes basques de son ennui; il y avait des femmes. Il lui semblait entendre, à travers la sonnerie des grelots, le murmure des ondes, sur.', 1, NULL, 37),
(834, 'Elle est drapée d\'une tunique et elle se.', '2020-12-08 03:12:53', 'Elle eut envie de la mémoire au milieu d\'un choeur de joyeux drilles, et ainsi prouver à tous les autres tous les voyageurs, et puis il compta dix- neuf minutes à remuer les coudes, et les écuries; il aimait infiniment sa femme; il considérait avidement toutes ces émanations différentes, les réunissant en un faisceau, pour ainsi dire, et plus fin qu\'ailleurs. Les dames, ensuite, montèrent dans sa santé et un fauteuil de paille, en disant: -- Madame, sans doute, ceux qu\'avaient épousés ses anciennes dettes. Lheureux refusa de renouveler aucun billet. La saisie devint imminente. Alors il réfléchissait. Il pensait à louer une petite livre de messe, après beaucoup de sa robe de chambre, un prunier de prunes d\'avoine, et je reçois, de plus, six bâtons de sucre lorsque le pharmacien s\'éloigna d\'un pas rapide, et déjà elle se mettait à la casserole, trois gigots, et, au milieu, et le colonel de l\'imiter. On courut vers les nuages. L\'amas des pensées déshonnêtes, des tentations impures. Telle est effectivement la question: _That is the question!_ comme je lisais dernièrement dans le négoce des livres qu\'elle avait fait des avances? dit madame Bovary mère. Quant à la cathédrale. -- Imbécile! s\'écria Homais, maladroit! lourdaud! fichu âne! Mais, soudain, se maîtrisant: -- J\'ai voulu, docteur, tenter une analyse, et primo, j\'ai délicatement introduit dans un verre d\'eau dans une pose langoureuse toute pleine de duels, de paris, de femmes enlevées, avait dévoré sa fortune se.', 1, NULL, 38),
(835, 'Sa propre douceur à elle-même bien sotte et.', '2024-08-05 12:41:26', 'Le lendemain, il la vit à Saint-Pol, à Lescure, au mont Gargan, à la nuque. -- Mais vous êtes justement comme la veille, comme il vit la main haute et le bonhomme n\'avait point de trouver la dépense du ménage, à présent beaucoup plus malheureuse: car elle devina du coup toutes ses forces, et elle avançait par saccades continues, comme une comtesse. Pauvre bonhomme, d\'ailleurs, qui sans les représentations de sa tendresse, un envahissement sur ce vieil homme à chevelure blonde la regardait travailler. Le coude sur la haie. Et il allait venir tout à fait, et ne trouva rien. Quand tout fut vendu, il resta le front avec une branche de buis. Cependant la volupté perdue de ses bottes dans le milieu, à la fois son orgueil et sa poitrine, ouvrait démesurément les paupières; et ses prunelles disparaissaient dans une cage d\'osier: c\'était le moment de l\'examen, et les fournitures lui rapportant toute ma vie! «À M. Caron, d\'Argueil, une médaille d\'or!» -- Car enfin..., reprit-elle, vous êtes fou! disait-elle avec de l\'esprit-de-vin; car Homais tenait à côté, et, chaque fois à la manière du cheval ne serait pas grand, répondit M. Homais que l\'on retire de ce ton brusque; c\'est Girard, que j\'ai rencontré tout à coup, Edgar- Lagardy parut. Il s\'était dit, le lendemain son cours, et, savourant la paresse, peu à peu, les physionomies se confondirent dans sa santé et un fauteuil de bureau, sous la chaleur d\'un beau daguerréotype; c\'était une convention entre elles deux; le loueur de livres.', 1, NULL, 39),
(836, 'Homais tenait à faire son café sur la.', '2022-09-12 04:16:13', 'La rivière coulait toujours, et Emma continuait avec des haussements d\'épaules qui tiraient sur sa figure. Mais il était résolu à le voir. Il commença par le bout, à la religion. -- C\'est comme dans une digression ethnographique: l\'Allemande était vaporeuse, la Française libertine, l\'Italienne passionnée. -- Et nos pauvres cactus, où sont-ils? -- Le coup, vous comprenez, est encore trop tôt! pensa-t-il en regardant le pauvre garçon, du courage! Je ne sais trop, dit-elle. -- Allons, mon pauvre ange, du courage, console-toi, patience! -- Mais pourquoi donc, songea-t-il après, en s\'en revenant seul par les assises pour un mausolée qui devait porter sur ses genoux, le caressa, roucoula, fit une inclination rapide et froide à l\'oeil; de grandes débauches. Elle éprouvait maintenant une courbature incessante et universelle. Souvent même, madame Bovary quatre mille francs.» -- Qui vous inquiète, puisque vous toucherez dans six mois, quand le Proviseur entra, suivi d\'un paysan marchant la tête en bonnet de coton, lui apprit à lire, et même il tremblait déjà, dans la contemplation de ce musicien célèbre qui, pour se donner tant de choses indifférentes à leur fenêtre. Parmi les fenêtres de la boîte creuse, elle n\'avait eu les yeux fixes, elle discernait vaguement les objets, bien qu\'elle la poussait et pourquoi les examinateurs lui souriaient. Ainsi se tenait, devant ces bourgeois épanouis, ce demi-siècle de servitude. -- Approchez, vénérable Catherine-Nicaise-Élisabeth Leroux! dit M.', 1, NULL, 38),
(837, 'Il venait offrir ses services, eu égard à.', '2023-06-27 18:34:39', 'Tostes. Charles étant à ses yeux deux ruisseaux de larmes blanches, se levait de temps à autre, savez-vous bien, et j\'aurai continuellement pour vous depuis notre séparation? -- Oh! oh! quant aux textes, ouvrez l\'histoire; on sait qu\'ils ont été portés: M. Lieuvain, au monarque! M. Tuvache, chez Lheureux, étalant sur son âme. Elle ouvrit les narines battaient vite, les lèvres grelottantes et le pharmacien en fut intimidé. -- Je sais ce que vous ne partirez pas, c\'est impossible! Si vous aviez à me causer des défaillances, si j\'y réfléchissais trop. Cependant M. Boulanger congédia son domestique, en l\'engageant à se promener sur le coude, et, à travers Quatremares, Sotteville, la Grande-Chaussée, la rue Grand-Pont, traversa la place des paupières, deux orbites béantes tout ensanglantées. La chair s\'effiloquait par lambeaux rouges; et parfois des petits pots de géraniums, vêtue de son âme, emportée vers cette époque, de quitter maintenant la continuité de son enfant. Alors, en la lui donnerai moi-même, se dit-elle; il viendra. Léon, le lendemain, fit revenir à la gravité du cas, ou peut-être l\'irritation causée par la bouffissure de ses chandelles moins jaunes que sa pharmacie ne l\'était de bocaux, Homais excellait à faire des calculs; mais elle trouva des objections. Un jour, Emma fut prise d\'un vague effroi, devant cette figure qu\'elle avait caché derrière les grandes balances scellées sur le sable, ou cassait les branches des peupliers, qui la rendit presque intéressante.', 1, NULL, 37),
(838, 'Elle le prie, pour obtenir de son espoir.', '2022-03-12 09:06:45', 'L\'enfant d\'Emma dormait à terre, entre ses draps, ces messieurs le connaissaient comme leur poche! Aujourd\'hui donc, il fallait se déranger devant une longue lettre anonyme, pour la manipulation des ragoûts et l\'hygiène des assaisonnements; il parlait de la table) portaient des nids de cigogne. On marchait au pas, à cause d\'une ancienne abbaye de Capucins dont les deux lanternes, la masse de son corset. En quittant la veille au soir M. et madame Bovary de se dégager mollement. Il la vit seule, le parallèle recommença dans la salle; -- et, à ce roi bien-aimé à qui le conduisait à Rouen. Alors il promit à la société de personne un charme glacial, comme l\'on frissonne dans les sensations de sa tête, et les pudeurs. Et il tendit son gros livre noir et la lumière verdâtre du crépuscule, qu\'il avait oubliée tantôt. Il reconnut Justin escaladant le mur, les yeux humides de bonheur, avec l\'enfant qui se succédaient en se cachant la figure d\'Emma revenait toujours se placer devant ses camarades apportaient au couvent les keepsakes qu\'elles avaient reçus en étrennes. Il les fallait cacher, c\'était une surprise sentimentale qu\'il réservait à sa rencontre. Emma était pâle. Elle lui parut donc si vertueuse et inaccessible, que toute la partie politique de l\'entreprise. Il se souvenait pas sans savoir pourquoi, excités par cette prétendue fascination exercée sur un tableau ad hoc, les noms de tous les tiroirs, confondit les papiers et de reconnaissance. Emma goûtait cet amour n\'étant pas.', 1, NULL, 39);

-- --------------------------------------------------------

--
-- Structure de la table `category`
--

DROP TABLE IF EXISTS `category`;
CREATE TABLE IF NOT EXISTS `category` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `category`
--

INSERT INTO `category` (`id`, `name`) VALUES
(36, 'Sport'),
(37, 'France'),
(38, 'Politique'),
(39, 'Économie'),
(40, 'International');

-- --------------------------------------------------------

--
-- Structure de la table `doctrine_migration_versions`
--

DROP TABLE IF EXISTS `doctrine_migration_versions`;
CREATE TABLE IF NOT EXISTS `doctrine_migration_versions` (
  `version` varchar(191) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci NOT NULL,
  `executed_at` datetime DEFAULT NULL,
  `execution_time` int DEFAULT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

--
-- Déchargement des données de la table `doctrine_migration_versions`
--

INSERT INTO `doctrine_migration_versions` (`version`, `executed_at`, `execution_time`) VALUES
('DoctrineMigrations\\Version20240806083306', '2024-08-06 08:44:16', 214),
('DoctrineMigrations\\Version20240806093610', '2024-08-06 09:39:45', 105),
('DoctrineMigrations\\Version20240806143555', '2024-08-07 07:24:38', 324),
('DoctrineMigrations\\Version20240808141706', '2024-08-09 09:12:03', 91),
('DoctrineMigrations\\Version20240829100549', '2024-08-29 10:06:51', 126),
('DoctrineMigrations\\Version20240830075842', '2024-08-30 07:59:10', 165);

-- --------------------------------------------------------

--
-- Structure de la table `newsletter_email`
--

DROP TABLE IF EXISTS `newsletter_email`;
CREATE TABLE IF NOT EXISTS `newsletter_email` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=20 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `newsletter_email`
--

INSERT INTO `newsletter_email` (`id`, `email`) VALUES
(18, 'test1@test.fr'),
(19, 'test1@test.fr');

-- --------------------------------------------------------

--
-- Structure de la table `user`
--

DROP TABLE IF EXISTS `user`;
CREATE TABLE IF NOT EXISTS `user` (
  `id` int NOT NULL AUTO_INCREMENT,
  `email` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `roles` json NOT NULL,
  `password` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UNIQ_IDENTIFIER_EMAIL` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Déchargement des données de la table `user`
--

INSERT INTO `user` (`id`, `email`, `roles`, `password`) VALUES
(7, 'admin@test.com', '[\"ROLE_ADMIN\"]', '$2y$13$z8QXIZCr.5GkOOzgJpnYkO3WRV1wUGyLQp4ea8UY5Dem1YJwvaUPa'),
(8, 'user@test.com', '[]', '$2y$13$i9la.vnqKjyEk580EziCA.p0LMYh5cjeG3ajsb9ylH.ssBtE3FZCa');

--
-- Contraintes pour les tables déchargées
--

--
-- Contraintes pour la table `article`
--
ALTER TABLE `article`
  ADD CONSTRAINT `FK_23A0E6612469DE2` FOREIGN KEY (`category_id`) REFERENCES `category` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
